@baseurl = http://localhost:3333

# @name create_event
POST {{baseurl}}/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100
}

###

# @name register_for_event
POST {{baseurl}}/events/ef779b42-4b72-4e3d-8390-2b60e49c6b46/attendees
Content-Type: application/json

{
  "name": "Oswaldo Oliveira",
  "email": "oswaldo.oliveira@email.com"
}
