@baseurl = http://localhost:3333

# @name create_event
POST {{baseurl}}/events
Content-Type: application/json

{
  "title": "New Event",
  "details": null,
  "maximumAttendees": 1
}

###

# @name register_for_event
POST {{baseurl}}/events/35088300-e4ec-4a12-9cbb-74df12f8a318/attendees
Content-Type: application/json

{
  "name": "Oswaldo Oliveira",
  "email": "oswaldo.oliveira@email.com"
}

###

# @name get_event
GET {{baseurl}}/events/35088300-e4ec-4a12-9cbb-74df12f8a318

###

# @name get_attendee_badge
GET {{baseurl}}/attendees/2/badge

###

# @name check_in
GET {{baseurl}}/attendees/2/check-in

