@baseurl = http://localhost:3333

# @name create_event
POST {{baseurl}}/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para quem é apaixonado por programação",
  "maximumAttendees": 100
}
